# Generated by Django 3.2.2 on 2021-05-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='south',
            name='image',
            field=models.ImageField(upload_to='media/media/pics'),
        ),
    ]
