# Generated by Django 3.2.2 on 2021-05-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_alter_south_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='south',
            new_name='south_breakfast',
        ),
    ]
