# Generated by Django 3.2.2 on 2021-05-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0008_south_dinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='north_dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='media/media/pics')),
                ('rupess', models.IntegerField()),
            ],
        ),
    ]
