# Generated by Django 3.2.2 on 2021-05-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0010_alter_north_dinner_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='north_dinner',
            old_name='rupess',
            new_name='rupees',
        ),
    ]
