# Generated by Django 3.2.2 on 2021-05-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0013_auto_20210528_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='south_lunch',
            name='rupees',
            field=models.CharField(max_length=15),
        ),
    ]
