# Generated by Django 3.2.2 on 2021-06-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0016_alter_south_lunch_rupees'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=40)),
                ('street_name', models.CharField(max_length=40)),
                ('phone_no', models.CharField(max_length=20)),
            ],
        ),
    ]
